export const cities = [
  { id: 1, name: "Cairo" },
  { id: 2, name: "Alexandria" },
  { id: 3, name: "Giza" },
  { id: 4, name: "Shubra El-Kheima" },
  { id: 5, name: "Port Said" },
  { id: 6, name: "Suez" },
  { id: 7, name: "Luxor" },
  { id: 8, name: "Asyut" },
  { id: 9, name: "Tanta" },
  { id: 10, name: "Ismailia" },
  { id: 11, name: "Damietta" },
  { id: 12, name: "Mansoura" },
  { id: 13, name: "Zagazig" },
  { id: 14, name: "Faiyum" },
  { id: 15, name: "Minya" },
  { id: 16, name: "Alexandria" },
  { id: 17, name: "Aswan" },
  { id: 18, name: "Damanhur" },
  { id: 19, name: "Beni Suef" },
  { id: 20, name: "Qena" },
  { id: 21, name: "Sohag" },
  { id: 22, name: "Kafr El Sheikh" },
  { id: 23, name: "Shibin El Kom" },
  { id: 24, name: "Banha" },
  { id: 25, name: "Arish" },
  { id: 26, name: "Mallawi" },
  { id: 27, name: "Bani Suwayf" },
  { id: 28, name: "Port Said" },
  { id: 29, name: "Tanta" },
  { id: 30, name: "Ismailia" },
  { id: 31, name: "Damietta" },
  { id: 32, name: "Mansoura" },
  { id: 33, name: "Zagazig" },
  { id: 34, name: "Faiyum" },
  { id: 35, name: "Minya" },
  { id: 36, name: "Alexandria" },
  { id: 37, name: "Aswan" },
  { id: 38, name: "Damanhur" },
  { id: 39, name: "Beni Suef" },
  { id: 40, name: "Qena" },
  { id: 41, name: "Sohag" },
  { id: 42, name: "Kafr El Sheikh" },
  { id: 43, name: "Shibin El Kom" },
  { id: 44, name: "Banha" },
  { id: 45, name: "Arish" },
  { id: 46, name: "Mallawi" },
  { id: 47, name: "Bani Suwayf" },
  { id: 48, name: "Port Said" },
  { id: 49, name: "Tanta" },
  { id: 50, name: "Ismailia" },
  { id: 51, name: "Damietta" },
  { id: 52, name: "Mansoura" },
  { id: 53, name: "Zagazig" },
  { id: 54, name: "Faiyum" },
  { id: 55, name: "Minya" },
  { id: 56, name: "Alexandria" },
  { id: 57, name: "Aswan" },
  { id: 58, name: "Damanhur" },
  { id: 59, name: "Beni Suef" },
  { id: 60, name: "Qena" },
  { id: 61, name: "Sohag" },
  { id: 62, name: "Kafr El Sheikh" },
  { id: 63, name: "Shibin El Kom" },
  { id: 64, name: "Banha" },
  { id: 65, name: "Arish" },
  { id: 66, name: "Mallawi" },
  { id: 67, name: "Bani Suwayf" },
  { id: 68, name: "Port Said" },
  { id: 69, name: "Tanta" },
  { id: 70, name: "Ismailia" },
  { id: 71, name: "Damietta" },
  { id: 72, name: "Mansoura" },
  { id: 73, name: "Zagazig" },
  { id: 74, name: "Faiyum" },
  { id: 75, name: "Minya" },
  { id: 76, name: "Alexandria" },
].sort((a, b) => (a.name > b.name ? 1 : -1));
